// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Radio: typeof import('./src/components/Radio.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
  }
}

export { }
