// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/base/Button.vue')['default']
    Divider: typeof import('./src/components/base/Divider.vue')['default']
    Input: typeof import('./src/components/base/Input.vue')['default']
    Label: typeof import('./src/components/base/Label.vue')['default']
    NumInput: typeof import('./src/components/base/NumInput.vue')['default']
    Radio: typeof import('./src/components/base/Radio.vue')['default']
    Select: typeof import('./src/components/base/Select.vue')['default']
    SvgIcon: typeof import('./src/components/base/SvgIcon.vue')['default']
    TextBoxColor: typeof import('./src/components/base/TextBoxColor.vue')['default']
    Title: typeof import('./src/components/base/Title.vue')['default']
  }
}

export { }
